#pragma once

#include "LowEditorApi.h"

#include "IconsLucide.h"

#include "LowUtilName.h"

// ICONS
#define LOW_EDITOR_ICON_CUBE ICON_LC_BOX
#define LOW_EDITOR_ICON_FILE ICON_LC_FILE
#define LOW_EDITOR_ICON_SWORD ICON_LC_SWORD
#define LOW_EDITOR_ICON_TRASH ICON_LC_TRASH_2
#define LOW_EDITOR_ICON_PLUS ICON_LC_PLUS
#define LOW_EDITOR_ICON_KEY ICON_LC_KEY_ROUND
#define LOW_EDITOR_ICON_FIGHT ICON_LC_SWORDS
#define LOW_EDITOR_ICON_SEARCH ICON_LC_SEARCH
#define LOW_EDITOR_ICON_CLEAR ICON_LC_ERASER
#define LOW_EDITOR_ICON_POSITION ICON_LC_MOVE_3D
#define LOW_EDITOR_ICON_PHYSICS ICON_LC_ATOM
#define LOW_EDITOR_ICON_MISSING ICON_LC_CIRCLE_HELP
#define LOW_EDITOR_ICON_SUN ICON_LC_SUN
#define LOW_EDITOR_ICON_BULB ICON_LC_LIGHTBULB
#define LOW_EDITOR_ICON_CYLINDER ICON_LC_CYLINDER
#define LOW_EDITOR_ICON_FLOPPY ICON_LC_SAVE
#define LOW_EDITOR_ICON_ROBOT ICON_LC_BOT
#define LOW_EDITOR_ICON_IMAGE ICON_LC_IMAGE
#define LOW_EDITOR_ICON_TEXT ICON_LC_TYPE
#define LOW_EDITOR_ICON_ELEMENT ICON_LC_SQUARE_DASHED
#define LOW_EDITOR_ICON_CONTROLLER ICON_CI_CIRCUIT_BOARD
#define LOW_EDITOR_ICON_CODE ICON_LC_CODE
#define LOW_EDITOR_ICON_SCRIPT ICON_LC_FILE_CODE
#define LOW_EDITOR_ICON_REFRESH ICON_LC_REFRESH_CW
#define LOW_EDITOR_ICON_FILE_SAVED ICON_LC_FILE_CHECK
#define LOW_EDITOR_ICON_FILE_MODIFIED ICON_LC_FILE_PEN
#define LOW_EDITOR_ICON_FILE_LOCKED ICON_LC_FILE_LOCK
#define LOW_EDITOR_ICON_STATUS_INFO ICON_LC_INFO
#define LOW_EDITOR_ICON_SKELETON ICON_LC_PERSON_STANDING

// ALIASES
#define LOW_EDITOR_ICON_ADD LOW_EDITOR_ICON_PLUS
#define LOW_EDITOR_ICON_DELETE LOW_EDITOR_ICON_TRASH
#define LOW_EDITOR_ICON_TRANSFORM LOW_EDITOR_ICON_POSITION
#define LOW_EDITOR_ICON_DIRECTIONAL_LIGHT LOW_EDITOR_ICON_SUN
#define LOW_EDITOR_ICON_POINT_LIGHT LOW_EDITOR_ICON_BULB
#define LOW_EDITOR_ICON_ENTITY LOW_EDITOR_CYLINDER
#define LOW_EDITOR_ICON_SAVE LOW_EDITOR_ICON_FLOPPY
#define LOW_EDITOR_ICON_ANIMATOR LOW_EDITOR_ICON_SKELETON

namespace Low {
  namespace Editor {
    LOW_EDITOR_API const char *
    get_icon_by_name(Util::Name p_IconName);
  }
} // namespace Low
