#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, set = 1, rgba32f) uniform image2D out_Color;
layout(set = 1, binding = 1) uniform sampler2D u_Texture;

vec2 get_texture_coords()
{
  ivec2 l_AbsolutePixel = ivec2(gl_GlobalInvocationID.xy);
  return vec2((float(l_AbsolutePixel.x) + 0.5) / 600.0,
              (float(l_AbsolutePixel.y) + 0.5) / 600.0);
}

void main()
{
  ivec2 xy_int = ivec2(gl_GlobalInvocationID.xy);

  vec3 ocolor = vec3(1.0) - texture(u_Texture, get_texture_coords()).xyz;

  imageStore(out_Color, xy_int, vec4(ocolor, 1.0));
}
