#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, set = 0, rgba32f) uniform image2D out_image;

vec2 get_texture_coords()
{
  ivec2 l_AbsolutePixel = ivec2(gl_GlobalInvocationID.xy);
  return vec2((float(l_AbsolutePixel.x) + 0.5) / 600.0,
              (float(l_AbsolutePixel.y) + 0.5) / 600.0);
}

void main()
{
  ivec2 xy_int = ivec2(gl_GlobalInvocationID.xy);

  imageStore(out_image, xy_int, vec4(vec3(0.3, 0.9, 0.7), 1.0));
}
